### ISSUE TITLE
Getting `Exception` when moving away from Page.

### ISSUE THREAD

**Issue by dgyesbreghs** [syncfusion/maui-toolkit#11]
When we move away from a certain page, we receive the following `Exception`.

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Syncfusion.Maui.Toolkit.TextInputLayout.SfTextInputLayout.OnTextInputViewTextChanged(Object sender, TextChangedEventArgs e) in C:\Git\RP\maui-toolkit\maui\src\TextInputLayout\SfTextInputLayout.Methods.cs:line 176
   at Microsoft.Maui.Controls.InputView.OnTextChanged(String oldValue, String newValue) in /_/src/Controls/src/Core/InputView/InputView.cs:line 150
   at Microsoft.Maui.Controls.InputView.<>c.<.cctor>b__96_0(BindableObject bindable, Object oldValue, Object newValue) in /_/src/Controls/src/Core/InputView/InputView.cs:line 13
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /_/src/Controls/src/Core/BindableObject.cs:line 662
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 587
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindingExpression.cs:line 163
   at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindingExpression.cs:line 78
   at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity) in /_/src/Controls/src/Core/Binding.cs:line 137
   at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean fromBindingContextChanged) in /_/src/Controls/src/Core/BindableObject.cs:line 679
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 364
   at Syncfusion.Maui.Toolkit.SfView.UpdateBindingContextToChild(BindableObject view) in C:\Git\RP\maui-toolkit\maui\src\Core\BaseView\DrawableLayoutView\SfView.cs:line 247
   at Syncfusion.Maui.Toolkit.SfView.OnBindingContextChanged() in C:\Git\RP\maui-toolkit\maui\src\Core\BaseView\DrawableLayoutView\SfView.cs:line 197
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in /_/src/Controls/src/Core/Element/Element.cs:line 766
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__94_0(BindableObject child, Object bc) in /_/src/Controls/src/Core/Element/Element.cs:line 577
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in /_/src/Controls/src/Core/BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in /_/src/Controls/src/Core/Element/Element.cs:line 575
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1244
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in /_/src/Controls/src/Core/View/View.cs:line 263
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in /_/src/Controls/src/Core/Layout/Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in /_/src/Controls/src/Core/Element/Element.cs:line 766
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__94_0(BindableObject child, Object bc) in /_/src/Controls/src/Core/Element/Element.cs:line 577
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in /_/src/Controls/src/Core/BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in /_/src/Controls/src/Core/Element/Element.cs:line 575
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1244
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in /_/src/Controls/src/Core/View/View.cs:line 263
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in /_/src/Controls/src/Core/Layout/Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetParent(Element value) in /_/src/Controls/src/Core/Element/Element.cs:line 427
   at Microsoft.Maui.Controls.Element.OnChildRemoved(Element child, Int32 oldLogicalIndex) in /_/src/Controls/src/Core/Element/Element.cs:line 614
   at Microsoft.Maui.Controls.VisualElement.OnChildRemoved(Element child, Int32 oldLogicalIndex) in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1268
   at Microsoft.Maui.Controls.Compatibility.Layout.OnInternalRemoved(View view, Int32 oldIndex) in /_/src/Controls/src/Core/LegacyLayouts/Layout.cs:line 616
   at Microsoft.Maui.Controls.Compatibility.Layout.InternalChildrenOnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Controls/src/Core/LegacyLayouts/Layout.cs:line 577
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Remove(Element item)
   at Microsoft.Maui.Controls.ContentPresenter.OnContentChanged(BindableObject bindable, Object oldValue, Object newValue) in /_/src/Controls/src/Core/ContentPresenter.cs:line 92
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 37
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22`

**Comment by PaulAndersonS** [comment]
Hi @dgyesbreghs,

We were able to replicate the issue at our end. We will fix the issue with priority at the earliest.
