### ISSUE TITLE
Hot reload causes app crash

### ISSUE THREAD

**Issue by riccardominato** [syncfusion/maui-toolkit#15]
I'm trying using hot reload on a page that contains a `SfTextInputLayout` component, but the app crashes everytime I change something, even if it doesn't have anything to do with the Syncfusion component.

```xaml
<inputLayout:SfTextInputLayout
    ContainerType="Outlined"
    ContainerBackground="White"
    InputViewPadding="15, 5"
    Hint="Email">
    <Entry
        Placeholder="Email"
        Keyboard="Email"
        Text="{Binding Email}" />
</inputLayout:SfTextInputLayout>
```

It happens both on Android and iOS.

If it have some relevance, I'm working on Rider on a MacBook.
Unfortunately I can't try on VSCode, but if this is a Rider issue, please let me know and I'll open a ticket to Jetbrains.

This is the exception.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Syncfusion.Maui.Toolkit.TextInputLayout.SfTextInputLayout.OnTextInputViewTextChanged(Object sender, TextChangedEventArgs e) in C:\Git\RP\maui-toolkit\maui\src\TextInputLayout\SfTextInputLayout.Methods.cs:line 176
   at Microsoft.Maui.Controls.InputView.OnTextChanged(String oldValue, String newValue) in /_/src/Controls/src/Core/InputView/InputView.cs:line 150
   at Microsoft.Maui.Controls.InputView.<>c.<.cctor>b__96_0(BindableObject bindable, Object oldValue, Object newValue) in /_/src/Controls/src/Core/InputView/InputView.cs:line 13
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /_/src/Controls/src/Core/BindableObject.cs:line 662
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 587
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindingExpression.cs:line 163
   at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindingExpression.cs:line 78
   at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity) in /_/src/Controls/src/Core/Binding.cs:line 137
   at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean fromBindingContextChanged) in /_/src/Controls/src/Core/BindableObject.cs:line 679
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 364
   at Syncfusion.Maui.Toolkit.SfView.UpdateBindingContextToChild(BindableObject view) in C:\Git\RP\maui-toolkit\maui\src\Core\BaseView\DrawableLayoutView\SfView.cs:line 247
   at Syncfusion.Maui.Toolkit.SfView.OnBindingContextChanged() in C:\Git\RP\maui-toolkit\maui\src\Core\BaseView\DrawableLayoutView\SfView.cs:line 197
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in /_/src/Controls/src/Core/Element/Element.cs:line 760
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in /_/src/Controls/src/Core/Element/Element.cs:line 571
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in /_/src/Controls/src/Core/BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in /_/src/Controls/src/Core/Element/Element.cs:line 569
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1244
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in /_/src/Controls/src/Core/View/View.cs:line 261
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in /_/src/Controls/src/Core/Element/Element.cs:line 760
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in /_/src/Controls/src/Core/Element/Element.cs:line 571
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in /_/src/Controls/src/Core/BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in /_/src/Controls/src/Core/Element/Element.cs:line 569
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1244
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in /_/src/Controls/src/Core/View/View.cs:line 261
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in /_/src/Controls/src/Core/Element/Element.cs:line 760
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in /_/src/Controls/src/Core/Element/Element.cs:line 571
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in /_/src/Controls/src/Core/BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in /_/src/Controls/src/Core/Element/Element.cs:line 569
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1244
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in /_/src/Controls/src/Core/View/View.cs:line 261
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in /_/src/Controls/src/Core/Layout/Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in /_/src/Controls/src/Core/Element/Element.cs:line 760
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in /_/src/Controls/src/Core/Element/Element.cs:line 571
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in /_/src/Controls/src/Core/BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in /_/src/Controls/src/Core/Element/Element.cs:line 569
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1244
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in /_/src/Controls/src/Core/View/View.cs:line 261
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in /_/src/Controls/src/Core/Layout/Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in /_/src/Controls/src/Core/Element/Element.cs:line 760
   at Microsoft.Maui.Controls.TemplatedView.SetChildInheritedBindingContext(Element child, Object context) in /_/src/Controls/src/Core/TemplatedView/TemplatedView.cs:line 72
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in /_/src/Controls/src/Core/Element/Element.cs:line 571
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in /_/src/Controls/src/Core/BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in /_/src/Controls/src/Core/Element/Element.cs:line 569
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1244
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in /_/src/Controls/src/Core/View/View.cs:line 261
   at Microsoft.Maui.Controls.ContentView.OnBindingContextChanged() in /_/src/Controls/src/Core/ContentView/ContentView.cs:line 23
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in /_/src/Controls/src/Core/BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Element.SetParent(Element value) in /_/src/Controls/src/Core/Element/Element.cs:line 427
   at Microsoft.Maui.Controls.Element.OnChildRemoved(Element child, Int32 oldLogicalIndex) in /_/src/Controls/src/Core/Element/Element.cs:line 608
   at Microsoft.Maui.Controls.VisualElement.OnChildRemoved(Element child, Int32 oldLogicalIndex) in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1268
   at Microsoft.Maui.Controls.TemplatedPage.OnChildRemoved(Element child, Int32 oldLogicalIndex) in /_/src/Controls/src/Core/TemplatedPage.cs:line 66
   at Microsoft.Maui.Controls.Element.RemoveLogicalChild(Element element, Int32 index) in /_/src/Controls/src/Core/Element/Element.cs:line 276
   at Microsoft.Maui.Controls.Element.RemoveLogicalChild(Element element) in /_/src/Controls/src/Core/Element/Element.cs:line 250
   at Microsoft.Maui.Controls.Page.InternalChildrenOnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Controls/src/Core/Page/Page.cs:line 708
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].RemoveAt(Int32 index)
   at Microsoft.Maui.Controls.TemplateUtilities.OnContentChanged(BindableObject bindable, Object oldValue, Object newValue) in /_/src/Controls/src/Core/TemplateUtilities.cs:line 64
   at Microsoft.Maui.Controls.BindableObject.ClearValueCore(BindableProperty property, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 149
   at Microsoft.Maui.Controls.BindableObject.ClearValue(BindableProperty property) in /_/src/Controls/src/Core/BindableObject.cs:line 89
   at JetBrains.HotReloadAgent.Maui.MauiProvider.PreCleanRootNode(Object root, Dictionary`2 itemsToCleanup)
   at JetBrains.HotReloadAgent.Maui.MauiProvider.CleanRootNode(Object root, Action action)
   at JetBrains.HotReloadAgent.Maui.MauiProvider.<>c__DisplayClass4_0.<<ReloadView>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 37
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

**Comment by riccardominato** [comment]
I think it related to #11.
